/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AES.java
 *
 * Created on Apr 22, 2011, 8:24:32 PM
 */

package NIS_version_3;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.math.BigInteger;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.swing.JFileChooser;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;

/**
 *
 * @author Anirudh
 */
public class AES extends javax.swing.JFrame {

    KeyGenerator keygen;
    SecretKey secretkey;
    Cipher cipher;

    int keysize;

    String datafilepath,encryptedfilepath;

    int encryptchunksize = 48;
    int decryptchunksize = 64;

    byte []dataencryptchunk,datadecryptchunk;

    JFileChooser fileChooser1,fileChooser2;
    
    /** Creates new form AES */
    public AES() {

        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }

        initComponents();

        fileChooser1 = new JFileChooser();
        fileChooser2 = new JFileChooser();
        
        fileChooser1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if(fileChooser1.getSelectedFile()!=null){
                    jTextField2.setText(fileChooser1.getSelectedFile().getPath());
                }
            }
        });

        fileChooser2.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if(fileChooser2.getSelectedFile()!=null){
                    jTextField1.setText(fileChooser2.getSelectedFile().getPath());
                }
            }
        });


        jTextArea3.setEnabled(false);
        jTextArea2.setEnabled(false);
        jTextArea1.setEnabled(false);

        jSpinner1.setModel(new SpinnerNumberModel(128,128,256,64));
        jSpinner2.setModel(new SpinnerNumberModel(16,16,80000,16));
        jSpinner2.setVisible(false);
        jLabel6.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Plain Text");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel3.setText("Cipher Text");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 390, 100));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 390, 100));

        jLabel1.setText("Plain Text");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 390, 100));

        jButton1.setText("Encrypt Plain Text");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        jButton2.setText("Decrypt Cipher Text");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        jButton3.setText("Browse");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 120, -1));

        jLabel4.setText("Data File Path");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 310, -1));

        jLabel5.setText("Key Length");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, -1));

        jCheckBox1.setText("Read Data In Chunks");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel6.setText("Chunk Size");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 80, -1));

        jButton5.setText("Open File");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 130, -1));

        jLabel7.setText("Encrypted File Path");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 310, -1));

        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            
            jTextArea3.setText("");
            encryptedfilepath = jTextField1.getText();

            if(jCheckBox1.isSelected()){
                encryptchunksize = (Integer) jSpinner2.getValue();
                decryptchunksize = encryptchunksize + 16;
            }
            
            keysize = (Integer) jSpinner1.getValue();

            keygen = KeyGenerator.getInstance("AES");
            keygen.init(keysize);

            secretkey = keygen.generateKey();

            cipher = Cipher.getInstance("AES");
            cipher.init(Cipher.ENCRYPT_MODE,secretkey);

            FileOutputStream fout = new FileOutputStream(encryptedfilepath);
            FileInputStream fin = new FileInputStream(datafilepath);

            dataencryptchunk = new byte[encryptchunksize];
            datadecryptchunk = new byte[decryptchunksize];

            byte []tempdata;
            int cnt;

            while( (cnt = fin.read(dataencryptchunk))!=-1){
                tempdata = cipher.doFinal(dataencryptchunk,0,cnt);
                System.out.println(cnt + "\t" + tempdata.length);
                fout.write(tempdata,0,tempdata.length);
                jTextArea3.setText(jTextArea3.getText() + new String(tempdata,0,cnt));
            }

            fout.close();
            fin.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        if(jCheckBox1.isSelected()){
            jLabel6.setVisible(true);
            jSpinner2.setVisible(true);
        }
        else{
            jLabel6.setVisible(false);
            jSpinner2.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fileChooser2.showSaveDialog(getContentPane());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{

            jTextArea2.setText("");
            datafilepath = jTextField2.getText();
            FileInputStream fin = new FileInputStream(datafilepath);

            byte [] data = new byte[80000];
            int cnt;

            while((cnt = fin.read(data))!=-1){
                jTextArea2.setText(jTextArea2.getText() + new String(data,0,cnt));
            }
            fin.close();


        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        fileChooser1.showOpenDialog(getContentPane());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            jTextArea1.setText("");
            cipher.init(Cipher.DECRYPT_MODE,secretkey);

            FileInputStream fin = new FileInputStream(encryptedfilepath);

            byte []tempdata;
            int cnt;

            System.out.println(datadecryptchunk.length);
            
            while( (cnt = fin.read(datadecryptchunk))!=-1){
                tempdata = cipher.doFinal(datadecryptchunk,0,cnt);
                System.out.println(tempdata.length);
                jTextArea1.setText(jTextArea1.getText() + new String(tempdata,0,tempdata.length));
            }

            fin.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
