/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DiffieHellman.java
 *
 * Created on Apr 22, 2011, 5:56:58 PM
 */

package NIS_version_3;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;

/**
 *
 * @author Anirudh
 */
public class DiffieHellman extends javax.swing.JFrame implements Runnable{

    boolean isserver;
    Socket clientsock;
    ServerSocket serversock;

    BufferedReader read;
    PrintStream write;

    long P,G;
    long Yclient,Yserver,Xclient,Xserver;
    long key;

    /** Creates new form DiffieHellman */
    public DiffieHellman() {
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Prime number P");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel2.setText("Generator G (primitive root of P)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 60, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Connect to Server");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Start a Server");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 10, 70));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 130, 10));

        jLabel3.setText("IP Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel4.setText("Port Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 120, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 90, -1));
        jSpinner1.setModel(new SpinnerNumberModel(80,0,65535,1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 310, -1));

        jButton1.setText("Send P and G");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 100, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 440, 10));

        jButton2.setText("Connect/Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel5.setText("Secret Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, -1));

        jButton3.setText("Calculate Y(a)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel6.setText("Y(b) Recieved");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 90, -1));

        jButton4.setText("Send Y(a)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 100, -1));

        jLabel7.setText("Key ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 80, -1));

        jButton5.setText("Generate Key");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel9.setText("Shared Y(a)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 80, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 440, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jButton2.setText("Connect");
        jTextField3.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jButton2.setText("Start");
        jTextField3.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if(jRadioButton1.isSelected()){
                clientsock = new Socket(jTextField1.getText(), (Integer) jSpinner1.getValue());

                if(clientsock.isConnected()){
                    jRadioButton1.setEnabled(false);
                    jRadioButton2.setEnabled(false);
                    jTextField3.setEnabled(false);
                    jSpinner1.setEnabled(false);
                    jButton2.setEnabled(false);

                    read = new BufferedReader(new InputStreamReader(clientsock.getInputStream()));
                    write = new PrintStream(clientsock.getOutputStream());

                    isserver = false;

                    JOptionPane.showMessageDialog(getContentPane(),"Connected to the server\nSelect P and G now");

                }
            }
            else{
                serversock = new ServerSocket((Integer) jSpinner1.getValue());

                if(serversock.isBound()){
                    jRadioButton1.setEnabled(false);
                    jRadioButton2.setEnabled(false);
                    jTextField3.setEnabled(false);
                    jSpinner1.setEnabled(false);
                    jButton2.setEnabled(false);

                    isserver = true;

                    jLabel9.setText("Shared Y(b)");
                    jButton3.setText("Calculate Y(b)");
                    jButton4.setText("Send Y(b)");
                    jLabel6.setText("Y(a) Recieved");
                    new Thread(this).start();
                    JOptionPane.showMessageDialog(getContentPane(),"Server Started");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(getContentPane(),ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        write.println(jTextField1.getText());
        write.println(jTextField2.getText());

        P = Long.parseLong(jTextField1.getText());
        G = Long.parseLong(jTextField2.getText());

        jTextField1.setEnabled(false);
        jTextField2.setEnabled(false);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if(isserver){
            Xserver = Long.parseLong(jTextField4.getText());
            Yserver = pow_mod(G,Xserver,P);
            jTextField7.setText("" + Yserver);
        }
        else{
            Xclient = Long.parseLong(jTextField4.getText());
            Yclient = pow_mod(G,Xclient,P);
            jTextField7.setText("" + Yclient);
        }

        jTextField4.setEnabled(false);
        jTextField7.setEnabled(false);
        jButton3.setEnabled(false);

        JOptionPane.showMessageDialog(getContentPane(),"Click on Send ASAP");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{

            if(isserver){
                write.println("" + Yserver);
                jButton4.setEnabled(false);

                jTextField5.setText(read.readLine());
                Yclient = Long.parseLong(jTextField5.getText());
            }
            else{
                write.println("" + Yclient);
                jButton4.setEnabled(false);

                jTextField5.setText(read.readLine());
                Yserver = Long.parseLong(jTextField5.getText());
            }

            jTextField5.setEnabled(false);
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(isserver){
            key = pow_mod(Yclient,Xserver,P);
        }
        else{
            key = pow_mod(Yserver,Xclient,P);
        }
        jTextField6.setText("" + key);

        jTextField6.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    private long pow_mod(long x,long y,long z){
        long ret = 1;

        System.out.println(x + "^" + y + "mod" + z);
        for(long i=1;i<=y;i++){
            ret = (x * ret) % z;
        }
        return ret;
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiffieHellman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    public void run() {
        try {
            jButton1.setEnabled(false);
            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);

            clientsock = serversock.accept();

            read = new BufferedReader(new InputStreamReader(clientsock.getInputStream()));
            write = new PrintStream(clientsock.getOutputStream());

            jTextField1.setText(read.readLine());
            jTextField2.setText(read.readLine());

            P = Long.parseLong(jTextField1.getText());
            G = Long.parseLong(jTextField2.getText());



        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

}
