/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MD5.java
 *
 * Created on Apr 22, 2011, 7:21:51 PM
 */

package NIS_version_3;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.math.BigInteger;
import java.security.MessageDigest;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Anirudh
 */
public class MD5 extends javax.swing.JFrame {

    String datafilepath,hashfilepath;
    JFileChooser fileChooser1,fileChooser2;
    byte [] digest;

    
    /** Creates new form MD5 */
    public MD5() {
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());        
        }
        catch(Exception e){
            System.out.println("Error :" + e.getMessage());
        }

        initComponents();
        
        fileChooser1 = new JFileChooser();
                
        fileChooser1.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if(fileChooser1.getSelectedFile()!=null){
                    jTextField1.setText(fileChooser1.getSelectedFile().getPath());
                }
            }
        });

        fileChooser2 = new JFileChooser();
        
        fileChooser2.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                if(fileChooser1.getSelectedFile()!=null){
                    jTextField2.setText(fileChooser2.getSelectedFile().getPath());
                }
            }
        });



    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Data File Path");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setText("Save Hash in the File:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 270, -1));

        jButton2.setText("Open File");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 110, -1));

        jButton3.setText("Generate Hash");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 110, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 270, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 270, -1));

        jButton1.setText("Save As");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 110, -1));

        jLabel3.setText("Hash Value of the data");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setText("Original Hash Value");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jButton4.setText("Make Random Changes in the Data File (optional)");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel5.setText("New Hash Value");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 270, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 270, -1));

        jButton5.setText("Compare Hash Values");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 550, 140));

        jLabel6.setText("Data Read From The File");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fileChooser1.showOpenDialog(getContentPane());

        try{
            datafilepath = jTextField1.getText();
            jTextArea1.setText("");
            FileInputStream fin = new FileInputStream(datafilepath);

            byte [] data = new byte[10000];
            int cnt;

            while((cnt = fin.read(data))!=-1){
                jTextArea1.setText(jTextArea1.getText() + new String(data));
            }

            fin.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fileChooser2.showSaveDialog(getContentPane());

        try{
            hashfilepath = jTextField2.getText();
            FileOutputStream fout = new FileOutputStream(hashfilepath);

            fout.write(digest);

            fout.close();

            jTextField1.setEnabled(false);
            jTextField2.setEnabled(false);
            jTextField3.setEnabled(false);

            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try{
            FileInputStream fin = new FileInputStream(datafilepath);

            MessageDigest messagedigest = MessageDigest.getInstance("MD5");

            byte [] data = new byte[1000];
            int cnt;
            
            while((cnt = fin.read(data))!=-1){
                messagedigest.update(data,0,cnt);
            }

            digest = messagedigest.digest();

            jTextField3.setText(new BigInteger(1,digest).toString(16));

            fin.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(getContentPane(),"Could not read from the file" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            FileOutputStream fout = new FileOutputStream(datafilepath);

            String datarandom = Math.random() + "";
            fout.write((datarandom).getBytes());
            jTextArea1.setText(datarandom);

            fout.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try{
            FileInputStream fin = new FileInputStream(datafilepath);

            MessageDigest messagedigest = MessageDigest.getInstance("MD5");

            byte [] data = new byte[1000];
            int cnt;

            while((cnt = fin.read(data))!=-1){
                messagedigest.update(data,0,cnt);
            }

            digest = messagedigest.digest();

            jTextField5.setText(new BigInteger(1,digest).toString(16));

            fin.close();

            //old hash value

            fin = new FileInputStream(hashfilepath);

            digest = new byte[16];
            fin.read(digest);

            jTextField4.setText(new BigInteger(1,digest).toString(16));

            fin.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(getContentPane(),"Could not read from the file" + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MD5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

}
