/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RemotePortScanning.java
 *
 * Created on Apr 22, 2011, 5:16:56 PM
 */

package NIS_version_3;

import java.net.Socket;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;

/**
 *
 * @author Anirudh
 */
public class RemotePortScanning extends javax.swing.JFrame {

    /** Creates new form RemotePortScanning */
    public RemotePortScanning() {
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }

        initComponents();

        jSpinner1.setModel(new SpinnerNumberModel(80,0,65535,1));
        jSpinner2.setModel(new SpinnerNumberModel(8000,0,65535,1));
        jSpinner3.setModel(new SpinnerNumberModel(0,0,255,1));
        jSpinner4.setModel(new SpinnerNumberModel(255,0,255,1));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Subnet IP Address");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Start from: Host Address");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setText("Start from: Port Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setText("End at: Port Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 70, -1));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 70, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 390, 150));

        jLabel5.setText("Results of Port Scanning");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton1.setText("Start Port Scanning");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel6.setText("End at: Host Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, -1));
        getContentPane().add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 60, -1));
        getContentPane().add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int starthostaddress = (Integer) jSpinner3.getValue();
        int endhostaddress = (Integer) jSpinner4.getValue();

        int startport = (Integer) jSpinner1.getValue();
        int endport = (Integer) jSpinner2.getValue();

        if(starthostaddress > endhostaddress){
            jTextArea1.setText("Enter proper IP Range");
            return;
        }

        if(startport > endport){
            jTextArea1.setText("Enter proper port number Range");
            return;
        }

        Socket clientsock;
        
        for(int i = starthostaddress; i<=endhostaddress; i++){
            jTextArea1.setText(jTextArea1.getText() + "IP Address = " + jTextField1.getText() + "." + i);
            jTextArea1.setText(jTextArea1.getText() + "\n\n");

            for(int j=startport;j<=endport;j++){
                try{
                    jTextArea1.setText(jTextArea1.getText() + "Port number = " + j + " : ");
                    clientsock = new Socket(jTextField1.getText() + "." + i,j);
                  
                    if(clientsock.isConnected()){
                        jTextArea1.setText(jTextArea1.getText() + "Port Open");
                    }
                    clientsock.close();
                }
                catch(Exception e){
                    jTextArea1.setText(jTextArea1.getText() + e.getMessage());
                }
                jTextArea1.setText(jTextArea1.getText() + "\n");
            }

            jTextArea1.setText(jTextArea1.getText() + "**********\n\n");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemotePortScanning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
